# Evaluación de contenidos 1 Módulo 2

# Ejercicios de NumPy

1. Importa la librería de NumPy.

In [1]:
import pandas as pd
import numpy as np
import os


2. Crea un array de 1 dimension y 10 elementos.

In [68]:
array_int = np.random.randint(50, size=10)

array_int

array([ 0, 31, 12,  6, 48, 35, 28, 45, 37, 26])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [123]:
array_vacio = np.empty(10, dtype=object)

for i in range(10):
    
    if array_int[i] % 2 == 0:
        array_vacio[i] = 'par'
    else:
        array_vacio[i] = 'impar'

print(array_vacio)

['par' 'impar' 'par' 'par' 'par' 'impar' 'par' 'impar' 'impar' 'par']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [78]:
array_cambiado = np.reshape(array_int, (2, 5))

array_cambiado

array([[ 0, 31, 12,  6, 48],
       [35, 28, 45, 37, 26]])

5. Extrae los elementos comunes de los siguientes arrays

array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [80]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [82]:
array_comunes = np.intersect1d(array1, array2)

array_comunes

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [85]:
array_diferentes = np.setdiff1d(array1, array2)

array_diferentes

array([1, 3, 5, 6])


7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [104]:
array_posicion = np.intersect1d(array1, array2, return_indices= True)

array_posicion

(array([2, 4]), array([1, 5]), array([1, 5]))

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [106]:
array_entero = np.random.randint(0, 51, (3,5))

array_entero

array([[12, 19, 49, 11, 29],
       [32, 11, 18, 50, 30],
       [38, 15, 20,  5,  6]])

In [107]:
# indexacion

pequeños = array_entero[array_entero < 10]
grandes = array_entero[array_entero > 40]

print(f'Los valores menores de 10 son {pequeños}')

print(f'Los valores mayores de 40 son {grandes}')

Los valores menores de 10 son [5 6]
Los valores mayores de 40 son [49 50]


9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [115]:
array_float = np.random.uniform(size =(5, 3,), low= 5, high = 10)

array_float

array([[8.43107695, 7.75440603, 5.83904186],
       [7.11666114, 6.60571175, 6.70766104],
       [7.32855777, 8.78246062, 7.48097737],
       [7.14025632, 8.31969417, 7.75269825],
       [7.59191896, 9.43199071, 8.17497276]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [118]:
tridimensional = np.random.randint(1, 21, (2, 4, 7))
tridimensional

array([[[ 6, 16, 17,  6,  9, 11, 19],
        [ 7, 13,  8,  6,  6, 16, 15],
        [ 4,  8, 18,  9, 13,  5,  8],
        [13, 11, 16, 17, 10, 12,  3]],

       [[11,  3,  4, 19, 20,  3,  2],
        [ 9,  7, 12, 13,  3,  2, 18],
        [ 2, 16, 15, 10,  8,  9, 11],
        [17,  1,  9,  9,  5,  1, 15]]])


11. Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [121]:
tri_transpose = np.transpose(tridimensional, (1, 2, 0))
tri_transpose

array([[[ 6, 11],
        [16,  3],
        [17,  4],
        [ 6, 19],
        [ 9, 20],
        [11,  3],
        [19,  2]],

       [[ 7,  9],
        [13,  7],
        [ 8, 12],
        [ 6, 13],
        [ 6,  3],
        [16,  2],
        [15, 18]],

       [[ 4,  2],
        [ 8, 16],
        [18, 15],
        [ 9, 10],
        [13,  8],
        [ 5,  9],
        [ 8, 11]],

       [[13, 17],
        [11,  1],
        [16,  9],
        [17,  9],
        [10,  5],
        [12,  1],
        [ 3, 15]]])