# Evaluación de contenidos 1 Módulo 2

# Ejercicios de NumPy

1. Importa la librería de NumPy.

In [3]:
import pandas as pd
import numpy as np
import os


2. Crea un array de 1 dimension y 10 elementos.

In [4]:
array_int = np.random.randint(50, size=10)

array_int

array([ 7,  0, 32, 37,  3, 10,  7,  8,  7,  9])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [5]:
'''Si en dtype ponemos =str solo saca la primera letra de 'par' o 'impar' '''
array_vacio = np.empty(10, dtype=object)

for i in range(10):
    
    if array_int[i] % 2 == 0:
        array_vacio[i] = 'par'
    else:
        array_vacio[i] = 'impar'

print(array_vacio)

['impar' 'par' 'par' 'impar' 'impar' 'par' 'impar' 'par' 'impar' 'impar']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [6]:
'''con el método reshape simplemente especificamos entre paréntesis la forma que queremos'''

array_cambiado = np.reshape(array_int, (2, 5))

array_cambiado

array([[ 7,  0, 32, 37,  3],
       [10,  7,  8,  7,  9]])

5. Extrae los elementos comunes de los siguientes arrays

array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
''' elementos comunes entre los dos arrays y ordenados'''

array_comunes = np.intersect1d(array1, array2)

array_comunes

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [9]:
''' elementos que están en A pero no B. Devuelve valores únicos, no como np.in1d()'''
array_diferentes = np.setdiff1d(array1, array2)

array_diferentes

array([1, 3, 5, 6])


7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [10]:
''' Primero lo hice así pero no me da todos los elementos y me lío interpretando los índices'''

array_posicion = np.intersect1d(array1, array2, return_indices= True)

array_posicion

(array([2, 4]), array([1, 5]), array([1, 5]))

In [17]:
'''La solución correcta es con np.where, que devuelve los indices donde se cumple la condición'''

posiciones = np.where(array1 == array2)

posiciones


(array([1, 3, 5, 7]),)

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [12]:
array_entero = np.random.randint(0, 51, (3,5))

array_entero

array([[21, 31, 27, 46, 17],
       [31,  8, 37, 11, 14],
       [50, 49, 45,  6, 34]])

In [20]:
'''Podemos usar los corchetes para que devuelva los valores donde se cumpla la condición. También con paréntesis y "|" '''

pequeños = array_entero[array_entero < 10]
grandes = array_entero[array_entero > 40]

print(f'Los valores menores de 10 son {pequeños}')

print(f'Los valores mayores de 40 son {grandes}')

Los valores menores de 10 son [8 6]
Los valores mayores de 40 son [46 50 49 45]


9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [14]:
'''Random uniform genera muestras aleatorias de distribución uniforme con el intervalo que le pasemos'''

array_float = np.random.uniform(size =(5, 3,), low= 5, high = 10)

array_float

array([[8.45742479, 6.71224406, 7.69467485],
       [6.21665655, 8.41891232, 5.0589105 ],
       [9.52679703, 8.42232458, 9.33805833],
       [8.76012796, 7.93094149, 7.12196427],
       [5.75901194, 6.39359983, 8.68566865]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [22]:
tridimensional = np.random.randint(1, 21, (2, 4, 7))
tridimensional

array([[[18,  6,  7, 20, 14, 19,  6],
        [ 1, 19, 10,  8, 18, 14, 19],
        [14, 20,  1, 13,  7, 11,  9],
        [ 5, 16, 12, 15, 18, 15, 17]],

       [[ 5,  9, 11, 18, 14,  6, 16],
        [ 2, 19,  7,  6, 20,  2, 12],
        [13,  5, 11,  7, 18,  7, 13],
        [20,  9,  5, 18,  5, 15, 12]]])


11. Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [16]:
tri_transpose = np.transpose(tridimensional, (1, 2, 0))
tri_transpose

array([[[ 9, 19],
        [17, 11],
        [10, 15],
        [18, 14],
        [16, 17],
        [12, 15],
        [ 4, 10]],

       [[13,  6],
        [ 1,  9],
        [13, 10],
        [ 1,  3],
        [ 3,  7],
        [ 7,  8],
        [15, 15]],

       [[10,  5],
        [18,  9],
        [11, 16],
        [18, 19],
        [ 1,  1],
        [10,  4],
        [11, 10]],

       [[17,  8],
        [14,  1],
        [16,  9],
        [13,  9],
        [ 6,  2],
        [17, 13],
        [19,  8]]])